name: Deploy
on:
  push:
    branches:
      - dev
jobs:
  mainPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: main-promotion
