name: Create deployment pull request
on:
  workflow_dispatch:

jobs:
  devToMainPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: dev-to-main-promotion
          base: main
          title: 'Production Deployment'
          body: 'This is an automated pull request to merge the dev branch into main.'
          reviewers: 'luisstd'
